[package]
name = "rust-ollama"
version = "0.1.0"
edition = "2021"

[dependencies]
ollama-rs = { version = "0.3.0", features = ["stream"] }
tokio = { version = "1.44.1", features = ["full"] }
tokio-stream = "0.1.17"
